baseURL = "https://blog.lijizhi.website/"
enableRobotsTXT = true              # 确保Hugo生成正确指令
languageCode = "zh"
defaultContentLanguage = "zh"
title = "脚踏实地"                         # site title  # 网站标题
theme = "zozo"
hasCJKLanguage = true                  # has chinese/japanese/korean ?  # 自动检测是否包含 中文\日文\韩文
summaryLength = 80                       # 首页文章摘要的长度
paginate = 15                      # shows the number of articles  # 首页显示文章数量
enableEmoji = false
googleAnalytics = ""                   # your google analytics id
disqusShortname = ""                   # your discuss shortname

pygmentsUseClasses = true
pygmentCodeFences = true
pygmentscodefencesguesssyntax = true
[author]                               # essential                     # 必需
name = "whitepure"

[blackfriday]
smartypants = false

# 多语言配置
# 英文
[languages.en]
weight = 0
languageName = "English"
[[languages.en.menu.main]]
url = "/"
name = "Home"
weight = 10
[[languages.en.menu.main]]
name = "archive"
weight = 20
identifier = "archive"
url = "/posts/"
[[languages.en.menu.main]]
name = "tags"
weight = 30
identifier = "tags"
url = "/tags/"
[[languages.en.menu.main]]
name = "about"
weight = 40
identifier = "about"
url = "/about/"

# 中文
[languages.zh]
weight = 0
languageName = "中文"
[[languages.zh.menu.main]]
name = "首页"
weight = 10
identifier = "home"
url = "/"
[[languages.zh.menu.main]]
name = "归档"
weight = 20
identifier = "archive"
url = "/posts/"
[[languages.zh.menu.main]]
name = "标签"
weight = 30
identifier = "tags"
url = "/tags/"
[[languages.zh.menu.main]]
name = "关于"
weight = 40
identifier = "about"
url = "/about/"


[build]
writeStats = true

[imaging]
quality = 80
anchor = "smart"
resampleFilter = "CatmullRom"


[params]
# 是否开启文章目录
toc = true
# site's subTitle  # 网站二级标题
subTitle = ""
# site's footer slogan  # 网站页脚标语
footerSlogan = "from 2020"
# site's keywords  # 网站关键字
keywords = ["whitepure博客","whiteppure","whitepure","Java","博客","技术博客"]
# site's description  # 网站描述
description = "技术博客 | 程序员面试指南与开发技巧分享，记录代码生涯的实战经验与生活思考。提供实用面经、编程干货，探讨职业成长与人生感悟。"
# 是否使用mathjax（数学公式）
enableMathJax = false
# display the article summary  # 是否显示文章摘要
enableSummary = true
mainSections = ["posts","post"]
# 是否开启导出功能 (仅支持pc)
enableExport = true
# 是否开启访问量展示
enableVisitor = true
# 博客开始日期 计算博客运行天数 必须配置且格式正确
blogStartDate = "2020-01-23"


# Valine.
# You can get your appid and appkey from https://leancloud.cn
# more info please open https://valine.js.org
# 评论系统 如果启用将appId和appKey一并设置
[params.valine]
enable = false
appId = "pRSrjsfbN6L1DUxgfqJWOMYP-gzGzoHsz"
appKey = "VPWpnDPGDM8Xhdlh5OvHOpak"
placeholder = "说点什么吧..."
visitor = true

# Your socail's url
[social]
github = "https://github.com/whiteppure/"
#  twitter = " "
#  facebook = " "
#  weibo = " "
#  instagram = " "

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

# 搜索
[outputs]
home = ["HTML", "RSS", "JSON"]

[sitemap]
filename = "sitemap.xml"
priority = 0.8
excludes = [
    "/drafts/*",
    "/vendor/*",
    "/node_modules/*"
]